
export const AFF = {
  SKYSCANNER_PID: "YOUR_SKYSCANNER_PID",
  BOOKING_AID: "YOUR_BOOKING_AID",
  AGODA_CID: "YOUR_AGODA_CID",
  EXPEDIA_CID: "YOUR_EXPEDIA_CID",
  HOTELS_COM_CID: "YOUR_HOTELS_COM_CID",
  KAYAK_AID: "YOUR_KAYAK_AID",
  KIWI_AFFIL_ID: "YOUR_KIWI_ID",
  OMIO_AID: "YOUR_OMIO_AID",
  TRAINLINE_PID: "YOUR_TRAINLINE_PID",
  EDREAMS_AID: "YOUR_EDREAMS_AID",
  DB_BAHN_ID: "YOUR_DB_ID",
  SNCF_ID: "YOUR_SNCF_ID",
  RYANAIR_AID: "YOUR_RYANAIR_AID",
  EASYJET_AID: "YOUR_EASYJET_AID",
  RENTALCARS_AID: "YOUR_RENTALCARS_AID",
  VIATOR_PID: "YOUR_VIATOR_PID",
  KLOOK_AFF: "YOUR_KLOOK_AFF"
}
