// Replace placeholders with your real IDs later.
export const AFF = {
  BOOKING_AID: "YOUR_BOOKING_AID",
  AGODA_CID: "YOUR_AGODA_CID",
  EXPEDIA_CID: "YOUR_EXPEDIA_CID",
  HOTELS_COM_PID: "YOUR_HOTELS_PID",
  SKYSCANNER_PID: "YOUR_SKYSCANNER_PID",
  KAYAK_AFFILID: "YOUR_KAYAK_ID",
  KIWI_AFFILID: "YOUR_KIWI_ID",
  VIATOR_AFFILID: "YOUR_VIATOR_PID",
  KLOOK_AFFILID: "YOUR_KLOOK_PID",
  RAIL_TRAINLINE_PID: "YOUR_TRAINLINE_PID",
  OMIO_PID: "YOUR_OMIO_PID",
  RENTALCARS_PID: "YOUR_RENTALCARS_PID"
};